name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the project directory on the client
            cd /var/www/html/bnp/client

            # Fetch all updates from the remote repository
            git fetch --all

            # Reset the current branch to match the remote main branch
            git reset --hard origin/main

            # Ensure environment variables are set up correctly
            cp .env.example .env

            # Build the Docker image
            docker build -t bnp-client .

            # Stop and remove any existing Docker container
            docker stop bnp-client || true
            docker rm bnp-client || true

            # Run the Docker container
            docker run -d --name bnp-client -p 4000:3000 bnp-client